
// This file has been generated by the GUI designer. Do not modify.
namespace EoD
{
	public partial class MissingInfoDialog
	{
		private global::Gtk.Label MILabel1;
		private global::Gtk.Button button19;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EoD.MissingInfoDialog
			this.WidthRequest = 500;
			this.Name = "EoD.MissingInfoDialog";
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(9));
			// Internal child EoD.MissingInfoDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.MILabel1 = new global::Gtk.Label ();
			this.MILabel1.Name = "MILabel1";
			this.MILabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			w1.Add (this.MILabel1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.MILabel1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Internal child EoD.MissingInfoDialog.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "dialog1_ActionArea";
			w3.Spacing = 10;
			w3.BorderWidth = ((uint)(5));
			w3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseUnderline = true;
			this.button19.Label = global::Mono.Unix.Catalog.GetString ("Quit");
			this.AddActionWidget (this.button19, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.button19]));
			w4.Expand = false;
			w4.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 234;
			this.Show ();
			this.button19.Clicked += new global::System.EventHandler (this.OnButton19Clicked);
		}
	}
}
