
// This file has been generated by the GUI designer. Do not modify.
namespace EoD
{
	public partial class Level5Dialog
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView textview1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeViewError1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeViewCorrection1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.VSeparator vseparator4;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.VSeparator vseparator5;
		private global::Gtk.Button button7;
		private global::Gtk.Button button8;
		private global::Gtk.Button button9;
		private global::Gtk.Button button10;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.Button button23;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EoD.Level5Dialog
			this.WidthRequest = 510;
			this.HeightRequest = 500;
			this.Name = "EoD.Level5Dialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Spell Checker");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			// Internal child EoD.Level5Dialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.WidthRequest = 400;
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.AcceptsTab = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow2.Add (this.textview1);
			this.vbox3.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow2]));
			w3.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Please note this is an early build for the spell checker - issues may be present." +
			"");
			this.label2.Wrap = true;
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 400;
			this.label1.Name = "label1";
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
			w5.Position = 2;
			w5.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeViewError1 = new global::Gtk.TreeView ();
			this.treeViewError1.CanFocus = true;
			this.treeViewError1.Name = "treeViewError1";
			this.GtkScrolledWindow.Add (this.treeViewError1);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w7.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeViewCorrection1 = new global::Gtk.TreeView ();
			this.treeViewCorrection1.CanFocus = true;
			this.treeViewCorrection1.Name = "treeViewCorrection1";
			this.GtkScrolledWindow1.Add (this.treeViewCorrection1);
			this.hbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow1]));
			w9.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w10.Position = 3;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.vbox2.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vseparator4]));
			w12.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.vbox2.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vseparator3]));
			w13.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vseparator5 = new global::Gtk.VSeparator ();
			this.vseparator5.Name = "vseparator5";
			this.vbox2.Add (this.vseparator5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vseparator5]));
			w14.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.Sensitive = false;
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("Ignore");
			this.vbox2.Add (this.button7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button7]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.Sensitive = false;
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("Change");
			this.vbox2.Add (this.button8);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button8]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.Sensitive = false;
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("Change All");
			this.vbox2.Add (this.button9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button9]));
			w17.Position = 5;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString ("Check Again");
			this.vbox2.Add (this.button10);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button10]));
			w18.Position = 6;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.vbox2.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vseparator2]));
			w19.Position = 7;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w21.Position = 0;
			// Internal child EoD.Level5Dialog.ActionArea
			global::Gtk.HButtonBox w22 = this.ActionArea;
			w22.Name = "__gtksharp_103_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_103_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button23 = new global::Gtk.Button ();
			this.button23.CanFocus = true;
			this.button23.Name = "button23";
			this.button23.UseUnderline = true;
			this.button23.Label = global::Mono.Unix.Catalog.GetString ("Done");
			this.AddActionWidget (this.button23, -10);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w22 [this.button23]));
			w23.Expand = false;
			w23.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 510;
			this.DefaultHeight = 500;
			this.button23.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.treeViewError1.CursorChanged += new global::System.EventHandler (this.OnTreeViewError1CursorChanged);
			this.treeViewCorrection1.CursorChanged += new global::System.EventHandler (this.OnTreeViewCorrection1CursorChanged);
			this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
			this.button10.Clicked += new global::System.EventHandler (this.CheckSpelling);
		}
	}
}
